### ISSUE TITLE
app.activeTag isn't equal to sprite.tags[]

### ISSUE THREAD

**Issue by erryox** [aseprite/api#22]
My sprite has only one tag, I write this code:
![изображение](https://user-images.githubusercontent.com/11627237/65325605-05d7b980-dbb8-11e9-86da-a904c09ae5d5.png)
and the result is:
![изображение](https://user-images.githubusercontent.com/11627237/65325645-18ea8980-dbb8-11e9-9f26-ddac7f85b775.png)

I think in version 1.2.13 everything worked as it should.

**Comment by dacap** [comment]
Hi @erryox, sorry for the delay with my answer. Actually each FrameTag object is just a "pseudo-object" that is referencing the same real Tag through an internal ID (scripting objects in Lua are wrappers of the internal objects, an almost everything is referenced through IDs instead of storing pointers). 

Not sure if this could be (or should be) fixed in a proper easy and proper way. You can compare two tags (e.g. `sprite.tags[1] == app.activeTags` should be true) because the `==` operator (`__eq` Lua metatable) for tags is [overloaded to compare their internal IDs](https://github.com/aseprite/aseprite/blob/484de6bd3a6fa7f9e30ec0bba0a880e1e1cc9bb1/src/app/script/tag_class.cpp#L29).

**Comment by erryox** [comment]
Hi,

This is not.
![изображение](https://user-images.githubusercontent.com/11627237/70799448-b8d04180-1dba-11ea-86ab-7ed96c3f4913.png)

**Comment by dacap** [comment]
🤔 It's strange, I'm just testing this:
```lua
local spr = app.activeSprite
print(spr.tags[1] == app.activeTag)
```
And it says true when I'm in the first tag and false in the second one:

<img width="271" alt="Screen Shot 2019-12-13 at 09 17 48" src="https://user-images.githubusercontent.com/39654/70799828-75a9aa80-1d89-11ea-97a5-e00569da9167.png" align=left>

<img width="233" alt="Screen Shot 2019-12-13 at 09 17 52" src="https://user-images.githubusercontent.com/39654/70799831-77736e00-1d89-11ea-80b0-fdcd4d1d9851.png" align=left>

**Comment by erryox** [comment]
Nevermind xD

If there was a bug before, now it has gone. In my screenshot above, you can see sprite.activeTa instead of sprite.activeTa**g**. Sorry :)

**Comment by dacap** [comment]
Oh that was the problem 😅 Anyway it's strange that Aseprite didn't say something about the undefined property `app.activeTa`, I'll take note about this problem to improve the error reporting in this case for the next version.
