### ISSUE TITLE
Incorrect Sprite:newFrame index argument?

### ISSUE THREAD

**Issue by ThKaspar** [aseprite/api#4]
Exactly as the title says - the number of frames is correct, however, they start from index/key 2 instead of 1 that documentation suggests.

**Comment by dacap** [comment]
🤔 this is strange, we've [a test to check this](https://github.com/aseprite/tests/blob/4d7f3036d84a4c37bd02ee491447705fcf4a8141/scripts/frames.lua#L14) and it looks like it's working correctly, but I'm not 100% sure.

**Comment by dacap** [comment]
@ThKaspar do you have a little lua script to test this bug?

**Comment by dacap** [comment]
Actually that is the expected behavior (I guess 🤔). The frame `1` is the first frame because `sprite.frames` is an Lua array, you will get the first frame as `sprite.frames[1]`, because Lua arrays are 1-based index, not 0-based index.

**Comment by dacap** [comment]
Basically the function should create a new frame in the given index.

**Comment by dacap** [comment]
Ohh I see, you're right. The docs don't match what the function does, and now I'm not sure what the function should do 😅

**Comment by ThKaspar** [comment]
The call is yours - both make sense but the one in the current docs match how GUI acts and from what I'm assuming It's a matter of finding in the current code where you subtract 1 from the passed argument. 😄

**Comment by dacap** [comment]
Maybe it should behave like the docs says (and as you can see, the GUI does too) so:

1. `sprite:newFrame(n)` should create a copy of the `n` frame (being 1 the first frame in the animation)
2. And `sprite:newFrame(0)` could create a new empty frame in the first position (just a special case to create empty frames in the beginning)

**Comment by dacap** [comment]
Ok, I think about this and some thoughts:

1. I guess the `Frame` object was a mistake 😆in the internal code there is no `Frame` object, and now I remember why: if you get a `Frame` object, and add/delete frames, the old `Frame` object will start pointing the frame in the same frame number, which will be other "frame", e.g. if we have 5 frames, and one frame object `a` pointing to the frame 3, and we add a new frame in 1, the object `a` will not make reference of the frame in position 4 (which is the new position of the frame where it was pointing).
2. `Sprite:newFrame(n)` and `Sprite:newEmptyFrame(n)` will create a copy of the frame in the given position and return the frame in the `n` position (no the next frame). This is because `Sprite:newEmptyFrame(1)` should make an empty frame in the position `1` and we want the `Frame` in that position, and `Sprite:newFrame(n)` should behave similar, but copying the frame in `n` (and returning the `n` frame, no `n+1`)
